version: '2'

services:
  web-challenge:
    build: .
    restart: always
    volumes:
      - ./dns:/dns
    ports:
      - "3001:80"
      - "8081:53"
      - "8081:53/udp"
    networks:
        default:  

networks:
    default: